### ISSUE TITLE
Mod is calling for the wrong version of MC on 1.19.2

### ISSUE THREAD

**Issue by Sunconure11** [DenisMasterHerobrine/TravellersBootsReloaded#1]
https://gist.github.com/Sunconure11/47f601a9c2a968e704b2c6ff15606223

@DenisMasterHerobrine

**Comment by DenisMasterHerobrine** [comment]
Hello, thanks for the report. Did you just put a 1.20.1 version of the mod to 1.19.2? Just rechecked both CurseForge and Modrinth pages and it seems to load just fine? Atleast the log states that you used a 1.20.1 version for a 1.19.2 modpack.

**Comment by Sunconure11** [comment]
This is what ATLauncher downloaded.

**Comment by DenisMasterHerobrine** [comment]
Just discussed in DMs, seems to be something wrong on CurseForge/Modrinth API side or on ATLauncher side, a `2.1.1-fabric` for MC 1.20.1 is wrongly marked as compatible with 1.19.2 for some reason.

If you're playing on 1.19.2 - you should use `2.0.1-fabric/2.0.1-forge` version.
If 1.20.1 - you should use `2.1.1-fabric/2.1.1-forge` version.
